name: Rust

on:
  push:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock", ".gihub/*"]
  pull_request:
    branches: [main]
    paths: ["**/*.rs", "**/Cargo.toml", "**/Cargo.lock"]

jobs:

  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: rustfmt
      - run: rustup component add rustfmt
      - run: cargo fmt -- --check

  check:
    name: Check
    strategy:
      matrix:
        features: ["", "std", "async", "std,async"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo check --no-default-features --features=${{ matrix.features}}

  clippy:
    name: Clippy
    strategy:
      matrix:
        features: ["", "std", "async", "std,async"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
          components: clippy
      - run: cargo clippy --no-default-features --features=${{ matrix.features}}

  test:
    name: Test Suite
    strategy:
      matrix:
        features: ["", "std", "async", "std,async"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: stable
      - run: cargo test --no-default-features --features=${{ matrix.features}}
